using Content.Client.UserInterface.Controls;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Omu.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectivesWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public AdminObjectivesWindow(AdminObjectivesWindowModel model) : this()
    {
        UpdateUi(model);
    }

    public AdminObjectivesWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateUi(AdminObjectivesWindowModel model)
    {
        CharacterIcon.SetEntity(model.Entity);
        CharacterName.Text = model.CharacterName;

        var roleType = _prototypeManager.Index(model.RoleTypeId);
        RoleType.Text = Loc.GetString(roleType.Name);
        RoleType.FontColorOverride = roleType.Color;

        if (model.RoleTypeSubType.HasValue)
            RoleTypeSubType.Text = Loc.GetString(model.RoleTypeSubType);
        RoleTypeSubType.FontColorOverride = roleType.Color;

        Objectives.RemoveAllChildren();
        foreach (var objectiveList in model.Objectives)
        {
            Objectives.AddChild(new Components.Objective.AdminObjectiveGroup(new Components.Objective.AdminObjectiveGroup.AdminObjectiveGroupModel(objectiveList.Key, objectiveList.Value)));
        }

        if (model.Targets.Count > 0)
            Objectives.AddChild(new Components.Target.AdminTargetGroup(new Components.Target.AdminTargetGroup.AdminTargetGroupModel(Loc.GetString("admin-view-objectives-window-sacrifice-targets"), model.Targets)));
    }
}

public sealed record AdminObjectivesWindowModel(Entity<ActorComponent> Entity, string CharacterName, ProtoId<RoleTypePrototype> RoleTypeId, LocId? RoleTypeSubType, Dictionary<string, List<Components.Objective.AdminObjectiveItem.AdminObjectiveItemModel>> Objectives, List<Components.Target.AdminTargetItem.AdminTargetItemModel> Targets);
