using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveTitle : Control
{
    public AdminObjectiveTitle(string text) : this()
    {
        UpdateText(text);
    }

    public AdminObjectiveTitle()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateText(string text)
    {
        Text.SetMarkupPermissive($"[bold]{text}[/bold]");
    }
}

