using Content.Shared.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminTargetGroup : Control
{
    public AdminTargetGroup(string title, List<AdminTargetItem.AdminObjectiveTargetModel> objectives) : this()
    {
        SetTargets(title, objectives);
    }

    public AdminTargetGroup()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetTargets(string title, List<AdminTargetItem.AdminObjectiveTargetModel> targets)
    {
        Title.UpdateText(title);

        foreach (var target in targets)
        {
            Objectives.AddChild(new AdminTargetItem(target));
        }
    }
}

