using Content.Shared.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveGroup : Control
{
    public AdminObjectiveGroup(string title, List<ObjectiveInfo> objectives) : this()
    {
        SetObjectives(title, objectives);
    }

    public AdminObjectiveGroup()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetObjectives(string title, List<ObjectiveInfo> objectives)
    {
        Title.UpdateText(title);

        foreach (var objective in objectives)
        {
            Objectives.AddChild(new AdminObjectiveItem(objective));
        }
    }
}

