using Content.Omu.Shared.Administration;
using Content.Shared.Objectives;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Omu.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminTargetItem : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public AdminTargetItem(AdminObjectiveTargetModel model) : this()
    {
        SetObjective(model);
    }

    public AdminTargetItem()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetObjective(AdminObjectiveTargetModel model)
    {
        TargetIcon.SetEntity(model.Target);

        TargetName.SetMessage(FormattedMessage.FromMarkupPermissive(model.TargetName));

        var job = _proto.Index(model.Job);
        TargetJob.SetMessage(FormattedMessage.FromMarkupPermissive(job.LocalizedName));
    }

    public record AdminObjectiveTargetModel(NetEntity Target, string TargetName, ProtoId<JobPrototype> Job);
}
