using Content.Shared.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Utility;

namespace Content.Omu.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveItem : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public AdminObjectiveItem(ObjectiveInfo objective) : this()
    {
        SetObjective(objective);
    }

    public AdminObjectiveItem()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetObjective(ObjectiveInfo objective)
    {
        var sprite = _entityManager.System<SpriteSystem>();

        Icon.Texture = sprite.Frame0(objective.Icon);

        var percentColor = objective.Progress == 0 ? Color.Red : objective.Progress >= 1 ? Color.Green : Color.Yellow;
        ObjectiveName.SetMessage(FormattedMessage.FromMarkupPermissive($"{objective.Title} [color={percentColor.ToHex()}]{(int) (objective.Progress * 100)}%[/color]"));
        if (string.IsNullOrWhiteSpace(objective.Description))
            ObjectiveDescription.Visible = false;
        ObjectiveDescription.SetMessage(FormattedMessage.FromMarkupPermissive(objective.Description));
    }
}
