using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Omu.Client.Administration.UI.Components.Objective;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveItem : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public AdminObjectiveItem(AdminObjectiveItemModel model) : this()
    {
        SetObjective(model);
    }

    public AdminObjectiveItem()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetObjective(AdminObjectiveItemModel model)
    {
        var sprite = _entityManager.System<SpriteSystem>();

        ObjectiveIcon.Texture = sprite.Frame0(model.Icon);

        var percentColor = model.Progress == 0 ? Color.Red : model.Progress >= 1 ? Color.Green : Color.Yellow;
        ObjectiveName.SetMessage(FormattedMessage.FromMarkupPermissive($"{model.Title} [color={percentColor.ToHex()}]{(int) (model.Progress * 100)}%[/color]"));
        if (string.IsNullOrWhiteSpace(model.Description))
            ObjectiveDescription.Visible = false;
        ObjectiveDescription.SetMessage(FormattedMessage.FromMarkupPermissive(model.Description));
    }

    public record AdminObjectiveItemModel(SpriteSpecifier Icon, string Title, string Description, float Progress);
}
