using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client.Administration.UI.Components.Objective;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveGroup : Control
{
    public AdminObjectiveGroup(AdminObjectiveGroupModel model) : this()
    {
        SetObjectives(model);
    }

    public AdminObjectiveGroup()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetObjectives(AdminObjectiveGroupModel model)
    {
        Title.SetMarkupPermissive(model.Title);

        foreach (var objective in model.Objectives)
        {
            Objectives.AddChild(new AdminObjectiveItem(objective));
        }
    }

    public record AdminObjectiveGroupModel(string Title, List<AdminObjectiveItem.AdminObjectiveItemModel> Objectives);
}

