- type: latheRecipePack
  id: SecurityEquipmentK9Armor
  recipes:
  - ClothingOuterArmorDuraVestK9 #K9 default vest - same stats a normal vest
  - ClothingOuterHardsuitCombatK9 # k9 combat suit - same stats a sec hardsuit
  - ClothingOuterArmorRiotK9 # k9 riot suit - same stats a riot suit
