- type: latheRecipePack
  id: SecurityEquipmentStaticDeltaV
  recipes:
  - ClothingOuterArmorDuraVestK9
  - ClothingOuterHardsuitCombatK9 # k9 combat suit
  - ClothingOuterHardsuitCombatRiotK9 # k9 riot suit
