using Content.Shared.Random;
using Robust.Shared.Prototypes;
using Content.Server.GameTicking.Rules;
using Robust.Shared.Random;
using Content.Shared.GameTicking.Components;
using Content.Shared.Silicons.Laws.Components;
using Content.Shared.Random.Helpers;
using Content.Server.Silicons.Laws;

namespace Content.Omu.Server.Gamerules.RoundstartAIvariation;

/// <summary>
///   Basic metric-based event scheduler.
///   Maintains a "chaos score", which is a number used to pick what events are rolled.
///   Events are weighted by their normal weight and by roughly how close they are to (the negative of) the current chaos score.
///   Chaos is passively generated by players, degenerated by ghosts, and changed by fired events' chaos scores.
///   For more information, see the summaries of the fields.
/// </summary>
[RegisterComponent, Access(typeof(RoundstartAIvariationsSystem))]
public sealed partial class RoundstartAIvariationComponent : Component
{
    /// <summary>
    ///   Weight table for roundstart lawsets
    /// </summary>
    [DataField]
    public ProtoId<WeightedRandomPrototype> RoundStartRules = "RandomRoundstartLawSets";
}

public sealed class RoundstartAIvariationsSystem : GameRuleSystem<RoundstartAIvariationComponent>
{
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly SiliconLawSystem _siliconLaw = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public override void Initialize()
    {
        base.Initialize();
    }

    protected override void Started(EntityUid uid,
        RoundstartAIvariationComponent component,
        GameRuleComponent gameRule,
        GameRuleStartedEvent args)
    {
        base.Started(uid, component, gameRule, args);

        var query = _entityManager.EntityQueryEnumerator<SiliconLawProviderComponent>();

        while (query.MoveNext(out var siliconUid, out var siliconLawProvider))
        {
            var meta = MetaData(siliconUid); // Omu
            if (meta.EntityPrototype?.ID == "StationAiBrain")
            {
                var weightedLawset = _prototypeManager.Index<WeightedRandomPrototype>(component.RoundStartRules);
                var lawset = weightedLawset.Pick(_random);

                siliconLawProvider.Lawset = _siliconLaw.GetLawset(lawset);
            }
        }
    }
}
