using System.Linq;
using System.Globalization;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Omu.Shared.Botany.PlantAnalyzer;

namespace Content.Omu.Client.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    /// <summary>
    /// Centralized color constants for consistent theming.
    /// </summary>
    private static class Colors
    {
        public const string DarkBackground = "#0a0a0a";
        public const string DarkerBackground = "#131313";
        public const string PanelBackground = "#121212";
        public const string PanelBorder = "#2b2b2b";
        public const string TextSecondary = "#999999";
        public const string TextTertiary = "#666666";
        public const string TextPrimary = "#CCCCCC";
        public const string WarningYellow = "#F7D117";
        public const string TextDefault = "#888888";
        public const string AlternateRowDark = "#1d1d1d";
        public const string BarWater = "#4DA6FF";
        public const string BarNutrition = "#FF9933";
        public const string BarToxin = "#DE4E4E";
        public const string BarWeed = "#8CC63F";
        public const string BarPest = "#F7D117";
        public const string HealthGreen = "#7CFC00";
    }

    private DateTime? _outOfRangeSince;

    private bool _outOfRangeResetReached;
    private double _outOfRangeResetSeconds = 5.0;
    private TimeSpan OutOfRangeReset => TimeSpan.FromSeconds(_outOfRangeResetSeconds);

    public double OutOfRangeResetSeconds
    {
        get => _outOfRangeResetSeconds;
        set => _outOfRangeResetSeconds = Math.Max(0.1, value);
    }

    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ConditionButton.OnPressed += _ => SetMode(0);
        GeneticsButton.OnPressed += _ => SetMode(1);
        TraitsButton.OnPressed += _ => SetMode(2);
        ChemistryButton.OnPressed += _ => SetMode(3);

        SetupBarColors();
        SetMode(0);
        ClearLabels();
    }

    private void SetupBarColors()
    {
        HealthBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.DarkBackground) };

        WaterBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.BarWater) };
        WaterBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.DarkBackground) };

        NutritionBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.BarNutrition) };
        NutritionBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.DarkBackground) };

        ToxinBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.BarToxin) };
        ToxinBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.DarkBackground) };

        WeedBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.BarWeed) };
        WeedBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.DarkBackground) };

        PestBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.BarPest) };
        PestBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(Colors.DarkBackground) };
    }

    private void SetMode(int mode)
    {
        ConditionContainer.Visible = mode == 0;
        GeneticsContainer.Visible = mode == 1;
        TraitsContainer.Visible = mode == 2;
        ChemistryContainer.Visible = mode == 3;

        // Update button pressed states to indicate the active tab
        ConditionButton.Pressed = mode == 0;
        GeneticsButton.Pressed = mode == 1;
        TraitsButton.Pressed = mode == 2;
        ChemistryButton.Pressed = mode == 3;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = base.GetDragModeFor(relativeMousePos);

        if (MinSize.X == MaxSize.X)
        {
            mode &= ~(DragMode.Left | DragMode.Right);
        }

        return mode;
    }

    public void Populate(PlantAnalyzerScannedState state)
    {
        if (state.Status == PlantAnalyzerStatus.NoData)
        {
            ShowNoDataState();
            return;
        }

        if (state.Status == PlantAnalyzerStatus.OutOfRange)
        {
            HandleOutOfRangeState();
            return;
        }

        ResetOutOfRangeState();
        PopulateSeedHeader(state);
        PopulateConditionTab(state);
        PopulateGeneticsTab(state);
        PopulateTraitsTab(state);
        PopulateChemistryTab(state);
    }

    private void ResetOutOfRangeState()
    {
        _outOfRangeSince = null;
        _outOfRangeResetReached = false;
    }

    private void HandleOutOfRangeState()
    {
        if (_outOfRangeResetReached)
        {
            ShowNoDataState();
            return;
        }

        if (_outOfRangeSince == null)
            _outOfRangeSince = DateTime.UtcNow;

        var elapsed = DateTime.UtcNow - _outOfRangeSince.Value;

        if (elapsed >= OutOfRangeReset)
        {
            _outOfRangeResetReached = true;
            _outOfRangeSince = null;
            ShowNoDataState();
        }
        else
        {
            ClearLabels();
            SeedSprite.SetEntity(null);
            SeedSprite.Visible = false;
            OutOfRangeSprite.Visible = true;
            StatusLabel.Text = Loc.GetString("plant-analyzer-window-out-of-range");
        }
    }

    private void PopulateSeedHeader(PlantAnalyzerScannedState state)
    {
        StatusLabel.Text = Loc.GetString("plant-analyzer-window-scanned");
        SeedSprite.Visible = true;
        OutOfRangeSprite.Visible = false;

        SeedNameLabel.Text = state.Name ?? Loc.GetString("plant-analyzer-na");

        if (state.Entity != null)
            SeedSprite.SetEntity(state.Entity.Value);
        else
            SeedSprite.SetEntity((EntityUid?)null);
    }

    private void PopulateConditionTab(PlantAnalyzerScannedState state)
    {
        PopulateHealthBar(state);
        PopulateConditionBars(state);
        PopulateWarnings(state.WarningsText);
        PopulateHarvestIndicator(state.HarvestReady);
    }

    private void PopulateHarvestIndicator(bool harvestReady)
    {
        HarvestReadyIndicator.Visible = false;

        if (!harvestReady)
            return;

        HarvestReadyIndicator.Visible = true;
        HarvestReadyIndicator.FontColorOverride = Color.FromHex(Colors.HealthGreen);
        HarvestReadyIndicator.Text = "⚘ " + Loc.GetString("plant-analyzer-ready-to-harvest");
    }

    private void PopulateHealthBar(PlantAnalyzerScannedState state)
    {
        HealthBar.MaxValue = state.MaxHealth ?? 100;
        HealthBar.Value = state.Health ?? 0;
        HealthBarLabel.Text = FormatHealth(state.Health, state.MaxHealth);
        SetHealthBarColor(state.Health, state.MaxHealth);
    }

    private void PopulateConditionBars(PlantAnalyzerScannedState state)
    {
        PopulateBar(WaterBar, WaterBarLabel, state.Water);
        PopulateBar(NutritionBar, NutritionBarLabel, state.Nutrition);
        PopulateBar(ToxinBar, ToxinBarLabel, state.ToxinLevel);
        PopulateBar(WeedBar, WeedBarLabel, state.WeedLevel);
        PopulateBar(PestBar, PestBarLabel, state.PestLevel);
    }

    private void PopulateBar(ProgressBar bar, Label label, float? value)
    {
        bar.Value = value == null || float.IsNaN(value.Value) || float.IsInfinity(value.Value) ? 0 : value.Value;
        label.Text = FormatPercent(value);
    }

    private void PopulateGeneticsTab(PlantAnalyzerScannedState state)
    {
        PopulateGeneticsStats(state);
        PopulateEnvironmentRequirements(state);
        PopulateMutationTargets(state);
    }

    private void PopulateGeneticsStats(PlantAnalyzerScannedState state)
    {
        YieldMultiplierLabel.Text = state.Yield != null ? state.Yield.Value.ToString() : Loc.GetString("plant-analyzer-na");
        PotencyLabel.Text = state.Potency != null ? ((int)state.Potency.Value).ToString() : Loc.GetString("plant-analyzer-na");
        MaturationLabel.Text = state.Maturation != null ? ((int)state.Maturation.Value).ToString() : Loc.GetString("plant-analyzer-na");
        ProductionLabel.Text = state.Production != null ? ((int)state.Production.Value).ToString() : Loc.GetString("plant-analyzer-na");
        PestResistanceLabel.Text = state.PestResistance != null ? ((int)state.PestResistance.Value).ToString() : Loc.GetString("plant-analyzer-na");
        ToxinResistanceLabel.Text = state.ToxinResistance != null ? ((int)state.ToxinResistance.Value).ToString() : Loc.GetString("plant-analyzer-na");
        WeedResistanceLabel.Text = state.WeedResistance != null ? ((int)state.WeedResistance.Value).ToString() : Loc.GetString("plant-analyzer-na");
    }

    private void PopulateEnvironmentRequirements(PlantAnalyzerScannedState state)
    {
        IdealTemperatureLabel.Text = state.IdealTemperature != null
            ? $"{state.IdealTemperature.Value - 273.15:0.##}°C ± {state.TemperatureTolerance:0.##}°C"
            : Loc.GetString("plant-analyzer-na");

        if (state.LowPressureTolerance != null && state.HighPressureTolerance != null)
        {
            var idealPressure = (state.LowPressureTolerance.Value + state.HighPressureTolerance.Value) / 2f;
            var pressureTolerance = (state.HighPressureTolerance.Value - state.LowPressureTolerance.Value) / 2f;
            IdealPressureLabel.Text = $"{idealPressure:0.##} kPa ± {pressureTolerance:0.##} kPa";
        }
        else
        {
            IdealPressureLabel.Text = Loc.GetString("plant-analyzer-na");
        }

        PopulateGasList(GeneticsConsumedGasesList, state.ConsumedGases, GeneticsConsumedGasesTotalLabel, "plant-analyzer-no-consumed-gases");
    }

    private void PopulateMutationTargets(PlantAnalyzerScannedState state)
    {
        MutationTargetsLabel.Text = state.MutationTargets != null && state.MutationTargets.Count > 0
            ? string.Join("\n", state.MutationTargets.Select(target => TitleCase(target)))
            : Loc.GetString("plant-analyzer-na");
    }

    private void PopulateTraitsTab(PlantAnalyzerScannedState state)
    {
        AddTraitBoxes(TraitsList, state.AllTraitsText);
    }

    private void PopulateChemistryTab(PlantAnalyzerScannedState state)
    {
        PopulateReagents(state);
        PopulateGases(state);
    }

    private void PopulateReagents(PlantAnalyzerScannedState state)
    {
        var inherentList = state.InherentReagents ?? new List<PlantReagentEntry>();
        var mutatedList = state.MutatedReagents ?? new List<PlantReagentEntry>();
        var totalReagentsAmount = inherentList.Sum(r => r.Amount) + mutatedList.Sum(r => r.Amount);

        TotalReagentsLabel.Text = (inherentList.Count > 0 || mutatedList.Count > 0)
            ? $"{totalReagentsAmount:0.##}u"
            : Loc.GetString("plant-analyzer-na");

        PopulateReagentList(InherentReagentsList, inherentList, InherentReagentsTotalLabel, "plant-analyzer-no-base-reagents");
        PopulateReagentList(MutatedReagentsList, mutatedList, MutatedReagentsTotalLabel, "plant-analyzer-no-additional-reagents");
    }

    private void PopulateReagentList(BoxContainer container, List<PlantReagentEntry> reagents, Label totalLabel, string emptyTextKey)
    {
        container.RemoveAllChildren();
        var total = reagents.Sum(r => r.Amount);
        totalLabel.Text = reagents.Count > 0 ? $"{total:0.##}u" : Loc.GetString("plant-analyzer-na");

        if (reagents.Count == 0)
        {
            AddPlaceholderPanel(container, Loc.GetString(emptyTextKey));
            return;
        }

        for (var i = 0; i < reagents.Count; i++)
        {
            AddReagentRow(container, reagents[i], i);
        }
    }

    private void PopulateGases(PlantAnalyzerScannedState state)
    {
        PopulateGasList(ConsumedGasesList, state.ConsumedGases, ConsumedGasesTotalLabel, "plant-analyzer-no-consumed-gases");
        PopulateGasList(ExudedGasesList, state.ExudedGases, ExudedGasesTotalLabel, "plant-analyzer-no-exuded-gases");
    }

    private void AddPlaceholderPanel(BoxContainer list, string text)
    {
        var placeholderPanel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex(Colors.PanelBackground),
                BorderColor = Color.FromHex(Colors.PanelBorder),
                BorderThickness = new Thickness(1)
            },
            Margin = new Thickness(0)
        };

        var placeholderBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(8, 8, 8, 8)
        };

        placeholderBox.AddChild(new Label
        {
            Text = text,
            HorizontalExpand = true,
            Align = Label.AlignMode.Left,
            FontColorOverride = Color.FromHex(Colors.TextSecondary)
        });

        placeholderPanel.AddChild(placeholderBox);
        list.AddChild(placeholderPanel);
    }

    private void ClearLabels()
    {
        SeedSprite.SetEntity(null);
        SeedSprite.Visible = false;
        OutOfRangeSprite.Visible = false;
        StatusLabel.Text = Loc.GetString("plant-analyzer-window-no-data");
        SeedNameLabel.Text = Loc.GetString("plant-analyzer-na");
        HealthBar.MaxValue = 100;
        HealthBar.Value = 0;
        HealthBarLabel.Text = Loc.GetString("plant-analyzer-na");
        SetHealthBarColor(null, null);
        WaterBar.Value = 0;
        WaterBarLabel.Text = Loc.GetString("plant-analyzer-na");
        NutritionBar.Value = 0;
        NutritionBarLabel.Text = Loc.GetString("plant-analyzer-na");
        ToxinBar.Value = 0;
        ToxinBarLabel.Text = Loc.GetString("plant-analyzer-na");
        WeedBar.Value = 0;
        WeedBarLabel.Text = Loc.GetString("plant-analyzer-na");
        PestBar.Value = 0;
        PestBarLabel.Text = Loc.GetString("plant-analyzer-na");
        PopulateWarnings(null);

        PotencyLabel.Text = Loc.GetString("plant-analyzer-na");
        YieldMultiplierLabel.Text = Loc.GetString("plant-analyzer-na");
        MaturationLabel.Text = Loc.GetString("plant-analyzer-na");
        ProductionLabel.Text = Loc.GetString("plant-analyzer-na");
        PestResistanceLabel.Text = Loc.GetString("plant-analyzer-na");
        ToxinResistanceLabel.Text = Loc.GetString("plant-analyzer-na");
        WeedResistanceLabel.Text = Loc.GetString("plant-analyzer-na");
        MutationTargetsLabel.Text = Loc.GetString("plant-analyzer-na");
        TraitsList.RemoveAllChildren();
        AddPlaceholderPanel(TraitsList, Loc.GetString("plant-analyzer-traits-none"));
        TotalReagentsLabel.Text = Loc.GetString("plant-analyzer-na");
        InherentReagentsTotalLabel.Text = Loc.GetString("plant-analyzer-na");
        MutatedReagentsTotalLabel.Text = Loc.GetString("plant-analyzer-na");
        ConsumedGasesTotalLabel.Text = Loc.GetString("plant-analyzer-na");
        GeneticsConsumedGasesTotalLabel.Text = Loc.GetString("plant-analyzer-na");
        ExudedGasesTotalLabel.Text = Loc.GetString("plant-analyzer-na");

        ConsumedGasesList.RemoveAllChildren();
        AddPlaceholderPanel(ConsumedGasesList, Loc.GetString("plant-analyzer-no-consumed-gases"));
        GeneticsConsumedGasesList.RemoveAllChildren();
        AddPlaceholderPanel(GeneticsConsumedGasesList, Loc.GetString("plant-analyzer-no-consumed-gases"));
        ExudedGasesList.RemoveAllChildren();
        AddPlaceholderPanel(ExudedGasesList, Loc.GetString("plant-analyzer-no-exuded-gases"));

        InherentReagentsList.RemoveAllChildren();
        AddPlaceholderPanel(InherentReagentsList, Loc.GetString("plant-analyzer-no-base-reagents"));
        MutatedReagentsList.RemoveAllChildren();
        AddPlaceholderPanel(MutatedReagentsList, Loc.GetString("plant-analyzer-no-additional-reagents"));
    }

    private void ShowNoDataState()
    {
        ClearLabels();
        SeedSprite.SetEntity(null);
        SeedSprite.Visible = false;
        OutOfRangeSprite.Visible = false;
        StatusLabel.Text = Loc.GetString("plant-analyzer-window-no-data");
    }

    private void PopulateWarnings(string? warningsText)
    {
        WarningsList.RemoveAllChildren();

        // Update header indicator
        WarningIndicator.Visible = false;

        if (string.IsNullOrWhiteSpace(warningsText))
        {
            WarningsList.AddChild(new Label
            {
                Text = Loc.GetString("plant-analyzer-warnings-none-message"),
                HorizontalExpand = true,
                Align = Label.AlignMode.Left,
                FontColorOverride = Color.FromHex(Colors.TextSecondary)
            });
            return;
        }

        var warningLines = warningsText
            .Split('\n')
            .Select(line => line.Trim())
            .Where(line => !string.IsNullOrEmpty(line))
            .Select(line => line.TrimStart('⚠').Trim())
            .ToList();

        // Show header indicator with count
        if (warningLines.Count > 0)
        {
            WarningIndicator.Visible = true;
            WarningIndicator.Text = $"⚠ {warningLines.Count} {Loc.GetString("plant-analyzer-warnings")}";
        }

        foreach (var warning in warningLines)
        {
            var warningRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4)
            };

            warningRow.AddChild(new Label
            {
                Text = "⚠",
                FontColorOverride = Color.FromHex(Colors.WarningYellow),
                Align = Label.AlignMode.Left,
                VerticalAlignment = VAlignment.Top,
                Margin = new Thickness(0, 0, 6, 0)
            });

            warningRow.AddChild(new RichTextLabel
            {
                Text = warning,
                HorizontalExpand = true,
                VerticalExpand = true
            });

            WarningsList.AddChild(warningRow);
        }
    }

    private static string TitleCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return value;

        try
        {
            return CultureInfo.InvariantCulture.TextInfo.ToTitleCase(value.ToLower(CultureInfo.InvariantCulture));
        }
        catch
        {
            return value;
        }
    }

    private void AddTraitBoxes(BoxContainer list, string? traitText)
    {
        list.RemoveAllChildren();

        // Check for empty/none state before unnecessary string operations
        if (string.IsNullOrWhiteSpace(traitText))
        {
            AddPlaceholderPanel(list, Loc.GetString("plant-analyzer-traits-none"));
            return;
        }

        var trimmedText = traitText.Trim();
        if (trimmedText.Length == 0 || trimmedText == Loc.GetString("plant-analyzer-traits-none"))
        {
            AddPlaceholderPanel(list, Loc.GetString("plant-analyzer-traits-none"));
            return;
        }

        var lines = trimmedText.Split('\n');
        var blocks = new List<(string Name, string Description)>();
        string? currentName = null;
        var currentDescription = new List<string>();

        foreach (var rawLine in lines)
        {
            var line = rawLine.TrimEnd();
            if (line.StartsWith("• "))
            {
                if (currentName != null)
                {
                    blocks.Add((currentName, string.Join("\n", currentDescription).Trim()));
                    currentDescription.Clear();
                }

                currentName = line.Substring(2).Trim();
                continue;
            }

            if (currentName != null)
            {
                if (!string.IsNullOrWhiteSpace(line))
                    currentDescription.Add(line);
            }
            else if (!string.IsNullOrWhiteSpace(line))
            {
                currentName = line.Trim();
            }
        }

        if (currentName != null)
        {
            blocks.Add((currentName, string.Join("\n", currentDescription).Trim()));
        }

        if (blocks.Count == 0)
        {
            AddTraitBoxes(list, null);
            return;
        }

        foreach (var block in blocks)
        {
            var traitPanel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex(Colors.PanelBackground),
                    BorderColor = Color.FromHex(Colors.PanelBorder),
                    BorderThickness = new Thickness(1)
                },
                Margin = new Thickness(0)
            };

            var traitBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(8, 8, 8, 8)
            };

            traitBox.AddChild(new Label
            {
                Text = block.Name,
                HorizontalExpand = true,
                FontColorOverride = Color.FromHex(Colors.TextPrimary)
            });

            if (!string.IsNullOrWhiteSpace(block.Description))
            {
                traitBox.AddChild(new RichTextLabel
                {
                    Text = block.Description,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 4, 0, 0)
                });
            }

            traitPanel.AddChild(traitBox);
            list.AddChild(traitPanel);
        }
    }

    private void PopulateGasList(BoxContainer list, List<PlantReagentEntry>? gases, Label totalLabel, string emptyTextKey)
    {
        list.RemoveAllChildren();
        var totalAmount = gases?.Sum(g => g.Amount) ?? 0f;
        totalLabel.Text = gases != null && gases.Count > 0 ? $"{totalAmount:0.##} moles" : Loc.GetString("plant-analyzer-na");

        if (gases == null || gases.Count == 0)
        {
            AddPlaceholderPanel(list, Loc.GetString(emptyTextKey));
            return;
        }

        for (var i = 0; i < gases.Count; i++)
        {
            AddReagentRow(list, gases[i], i, "moles");
        }
    }

    private void SetHealthBarColor(float? health, float? maxHealth)
    {
        if (HealthBar.ForegroundStyleBoxOverride == null)
        {
            HealthBar.ForegroundStyleBoxOverride = new StyleBoxFlat();
        }

        if (HealthBar.BackgroundStyleBoxOverride == null)
        {
            HealthBar.BackgroundStyleBoxOverride = new StyleBoxFlat();
        }

        var fillColor = (health != null && maxHealth != null && maxHealth > 0)
            ? Color.FromHsv(new Vector4(0.33f * Math.Clamp(health.Value / maxHealth.Value, 0f, 1f), 1f, 0.55f, 1f))
            : Color.FromHex("#444444");

        ((StyleBoxFlat) HealthBar.ForegroundStyleBoxOverride).BackgroundColor = fillColor;
        ((StyleBoxFlat) HealthBar.BackgroundStyleBoxOverride).BackgroundColor = Color.FromHex(Colors.DarkBackground);
    }

    private void AddReagentRow(BoxContainer list, PlantReagentEntry r, int i, string unit = "u")
    {
        var color = Color.FromHex(r.ColorHex);
        var rowColor = i % 2 == 0 ? Color.FromHex(Colors.AlternateRowDark) : Color.FromHex(Colors.DarkerBackground);
        var row = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat { BackgroundColor = rowColor },
            Margin = new Thickness(0, 0, 0, 0)
        };

        var innerRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 0)
        };

        var colorPanel = new PanelContainer
        {
            MinWidth = 8,
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat { BackgroundColor = color },
            Margin = new Thickness(0, 0, 6, 0)
        };

        innerRow.AddChild(colorPanel);
        innerRow.AddChild(new Label { Text = r.Name ?? Loc.GetString("plant-analyzer-unknown-plant"), HorizontalExpand = true, Align = Label.AlignMode.Left });

        var amount = ValidateReagentAmount(r.Amount);
        var display = r.DisplayAmount ?? amount.ToString("0.##");
        var amountText = unit == "moles" ? display + " " + unit : display + unit;

        innerRow.AddChild(new Label { Text = amountText, Align = Label.AlignMode.Right, Margin = new Thickness(0, 0, 6, 0) });
        row.AddChild(innerRow);
        list.AddChild(row);
    }

    /// <summary>
    /// Validate and clamp reagent amount, handling NaN and Infinity values.
    /// </summary>
    private static float ValidateReagentAmount(float amount)
    {
        if (float.IsNaN(amount) || float.IsInfinity(amount))
            return 0f;
        return amount;
    }

    private void SetBarColor(ProgressBar bar, Color color)
    {
        if (bar.ForegroundStyleBoxOverride == null)
        {
            bar.ForegroundStyleBoxOverride = new StyleBoxFlat();
        }

        if (bar.BackgroundStyleBoxOverride == null)
        {
            bar.BackgroundStyleBoxOverride = new StyleBoxFlat();
        }

        ((StyleBoxFlat) bar.ForegroundStyleBoxOverride).BackgroundColor = color;
        ((StyleBoxFlat) bar.BackgroundStyleBoxOverride).BackgroundColor = Color.FromHex(Colors.DarkBackground);
    }

    private static string FormatPercent(float? value)
    {
        if (value == null || float.IsNaN(value.Value) || float.IsInfinity(value.Value))
            return Loc.GetString("plant-analyzer-na");

        return ((int) value.Value).ToString() + "%";
    }

    private static string FormatHealth(float? health, float? maxHealth)
    {
        if (health == null || maxHealth == null || maxHealth == 0 || float.IsNaN(health.Value) || float.IsNaN(maxHealth.Value))
            return Loc.GetString("plant-analyzer-na");

        var percent = (int)(Math.Clamp(health.Value / maxHealth.Value, 0f, 1f) * 100f);
        return percent.ToString() + "%";
    }

}
