// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Omu.Common.CCVar;
using Content.Shared._Omu.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Omu.Lobby.Ui.Speech;

[GenerateTypedNameReferences]
public sealed partial class SpeechTab : BoxContainer
{
    public event Action<List<SpeechReplacement>>? OnReplacementsChanged;

    private readonly int _maxReplacements;
    private readonly int _maxLength;

    public SpeechTab(IConfigurationManager configManager)
    {
        RobustXamlLoader.Load(this);

        _maxReplacements = configManager.GetCVar(OmuCVars.SpeechReplacementsMax);
        _maxLength = configManager.GetCVar(OmuCVars.SpeechReplacementLength);
        ReplacementsSection.Visible = _maxReplacements > 0;

        AddButton.OnPressed += _ =>
        {
            AddRow(new SpeechReplacement());
            Refresh();
        };
    }

    public void AddAccents(Control accents)
    {
        AccentsContainer.AddChild(accents);
    }

    public void SetReplacements(IReadOnlyList<SpeechReplacement> replacements)
    {
        RowsContainer.DisposeAllChildren();
        foreach (var replacement in replacements)
        {
            AddRow(replacement);
        }

        Refresh();
    }

    private void AddRow(SpeechReplacement replacement)
    {
        var row = new ReplacementRow(replacement, _maxLength);
        row.Word.OnTextChanged += _ => EmitChanged();
        row.Replacement.OnTextChanged += _ => EmitChanged();
        row.RemoveButton.OnPressed += _ =>
        {
            RowsContainer.RemoveChild(row);
            EmitChanged();
        };
        RowsContainer.AddChild(row);
    }

    private void EmitChanged()
    {
        Refresh();
        var replacements = RowsContainer.Children
            .OfType<ReplacementRow>()
            .Where(row => row.Word.Text.Length > 0 || row.Replacement.Text.Length > 0)
            .Select(row => new SpeechReplacement { Word = row.Word.Text, Replacement = row.Replacement.Text })
            .ToList();
        OnReplacementsChanged?.Invoke(replacements);
    }

    private void Refresh()
    {
        var count = RowsContainer.ChildCount;
        var full = count >= _maxReplacements;
        CountLabel.Text = Loc.GetString("speech-tab-replacements-count", ("count", count), ("max", _maxReplacements));
        EmptyLabel.Visible = count == 0;
        AddButton.Disabled = full;
        if (full)
            CountBadge.AddStyleClass(StyleClass.Negative);
        else
            CountBadge.RemoveStyleClass(StyleClass.Negative);
    }

    private sealed class ReplacementRow : PanelContainer
    {
        public readonly LineEdit Word;
        public readonly LineEdit Replacement;
        public readonly TextureButton RemoveButton;

        public ReplacementRow(SpeechReplacement replacement, int maxLength)
        {
            AddStyleClass(SpeechTabSheetlet.CardClass);

            Word = new LineEdit
            {
                MinWidth = 220,
                Text = replacement.Word,
                PlaceHolder = Loc.GetString("speech-tab-replacements-word"),
                IsValid = text => text.Length <= maxLength,
            };
            Replacement = new LineEdit
            {
                MinWidth = 220,
                Text = replacement.Replacement,
                PlaceHolder = Loc.GetString("speech-tab-replacements-replacement"),
                IsValid = text => text.Length <= maxLength,
            };
            RemoveButton = new TextureButton
            {
                StyleClasses = { StyleClass.CrossButtonRed },
                ToolTip = Loc.GetString("speech-tab-replacements-remove"),
                VerticalAlignment = VAlignment.Center,
                Scale = new Vector2(0.75f, 0.75f),
            };

            var content = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 6,
            };
            content.AddChild(Word);
            content.AddChild(new Label
            {
                Text = Loc.GetString("speech-tab-replacements-becomes"),
                StyleClasses = { StyleClass.LabelWeak },
                VerticalAlignment = VAlignment.Center,
            });
            content.AddChild(Replacement);
            content.AddChild(RemoveButton);
            AddChild(content);
        }
    }
}
