using System.Linq;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._DV.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    private const string IndentedNewline = "\n   ";

    // health bar thresholds (percentage)
    private const float HealthGoodPct = 66f;
    private const float HealthWarnPct = 33f;

    // yield thresholds (unit count)
    private const int YieldHigh = 8;
    private const int YieldGood = 4;
    private const int YieldLow  = 2;

    // potency thresholds (percentage)
    private const float PotencyHigh = 80f;
    private const float PotencyMid  = 50f;
    private const float PotencyLow  = 20f;

    // ui colors (shared across all stat fields)
    private static readonly Color ColorGood    = Color.FromHex("#7ecd48"); // healthy green
    private static readonly Color ColorGoodAlt = Color.FromHex("#a8e070"); // lighter green
    private static readonly Color ColorWarn    = Color.FromHex("#e8a837"); // warning orange
    private static readonly Color ColorDanger  = Color.FromHex("#e05252"); // danger red
    private static readonly Color ColorCyan    = Color.FromHex("#4ecdc4"); // self-harvest cyan
    private static readonly Color ColorGold    = Color.FromHex("#f0c040"); // high potency gold
    private static readonly Color ColorGoldDim = Color.FromHex("#d4a830"); // mid potency gold

    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(PlantAnalyzerScannedSeedMessage msg)
    {
        NoData.Visible = false;
        Tabs.Visible = true;

        // ---- dead banner + name colour ----
        if (msg.IsTray && msg.IsDead)
        {
            DeadBanner.Visible = true;
            PlantName.FontColorOverride = ColorDanger;
        }
        else
        {
            DeadBanner.Visible = false;
            PlantName.FontColorOverride = ColorGood;
        }

        var nameKey = msg.IsTray ? "plant-analyzer-name-tray" : "plant-analyzer-name-seed";
        PlantName.Text = Loc.GetString(nameKey, ("name", Loc.GetString(
            string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown" : msg.SeedName)));

        // ---- health row (trays only) ----
        if (msg.IsTray)
        {
            HealthRow.Visible = true;
            var pct = msg.PlantMaxHealth > 0f ? msg.PlantHealth / msg.PlantMaxHealth * 100f : 0f;
            PlantHealthLabel.Text = $"{msg.PlantHealth:F0} / {msg.PlantMaxHealth:F0}  ({pct:F0}%)";
            PlantHealthLabel.FontColorOverride = pct switch
            {
                > HealthGoodPct => ColorGood,
                > HealthWarnPct => ColorWarn,
                _               => ColorDanger,
            };
        }
        else
        {
            HealthRow.Visible = false;
        }

        // ---- harvest type - coloured per type ----
        HarvestRepeat.Text = Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}");
        HarvestRepeat.FontColorOverride = msg.HarvestType switch
        {
            PlantAnalyzerHarvestType.Repeat      => ColorGood,  // perennial - keeps giving
            PlantAnalyzerHarvestType.SelfHarvest => ColorCyan,  // self-harvest - automatic
            _                                    => ColorWarn,   // ephemeral - one-shot
        };

        // ---- growth stats - value only, colour is fixed per field ----
        PlantYield.Text    = $"{msg.SeedYield:D0}";
        Potency.Text       = $"{msg.SeedPotency:F0}%";
        Lifespan.Text      = $"{msg.Lifespan:F1}";
        Maturation.Text    = $"{msg.Maturation:F1}";
        Production.Text    = $"{msg.Production:F1}";
        GrowthStages.Text  = $"{msg.GrowthStages:D0}";
        Endurance.Text     = $"{msg.Endurance:F0}";

        // yield colour scales: high is good
        PlantYield.FontColorOverride = msg.SeedYield switch
        {
            >= YieldHigh => ColorGood,
            >= YieldGood => ColorGoodAlt,
            >= YieldLow  => ColorWarn,
            _            => ColorDanger,
        };

        // potency colour scales: high is good
        Potency.FontColorOverride = msg.SeedPotency switch
        {
            >= PotencyHigh => ColorGold,
            >= PotencyMid  => ColorGoldDim,
            >= PotencyLow  => ColorWarn,
            _              => ColorDanger,
        };

        // ---- chemistry ----
        Chemicals.Text    = Loc.GetString("plant-analyzer-chemicals",    ("value", BuildList(msg.Chemicals)));
        ConsumeGases.Text = Loc.GetString("plant-analyzer-consume-gases", ("value", BuildList(msg.ConsumeGases)));
        ExudeGases.Text   = Loc.GetString("plant-analyzer-exude-gases",   ("value", BuildList(msg.ExudeGases)));

        // ---- tolerances tab - value only ----
        NutrientUsage.Text   = $"{msg.NutrientConsumption:F2} u/stage";
        WaterUsage.Text      = $"{msg.WaterConsumption:F2} u/stage";
        IdealHeat.Text       = $"{msg.IdealHeat:F0} K";
        HeatTolerance.Text   = $"±{msg.HeatTolerance:F1} K";
        IdealLight.Text      = $"{msg.IdealLight:F1} cd";
        LightTolerance.Text  = $"±{msg.LightTolerance:F1} cd";
        ToxinsTolerance.Text = $"{msg.ToxinsTolerance:F1}";
        LowPressure.Text     = $"{msg.LowPressureTolerance:F1} kPa";
        HighPressure.Text    = $"{msg.HighPressureTolerance:F1} kPa";
        PestTolerance.Text   = $"{msg.PestTolerance:F1}";
        WeedTolerance.Text   = $"{msg.WeedTolerance:F1}";

        // ---- mutations tab ----
        var mutList = new StringBuilder();
        if (msg.Mutations == PlantMutationFlags.None)
        {
            mutList.Append(IndentedNewline);
            mutList.Append(Loc.GetString("plant-analyzer-mutations-none"));
        }
        else
        {
            if (msg.Mutations.HasFlag(PlantMutationFlags.TurnIntoKudzu))
                AppendMutation(mutList, "plant-analyzer-mut-kudzu");
            if (msg.Mutations.HasFlag(PlantMutationFlags.Seedless))
                AppendMutation(mutList, "plant-analyzer-mut-seedless");
            if (msg.Mutations.HasFlag(PlantMutationFlags.Ligneous))
                AppendMutation(mutList, "plant-analyzer-mut-ligneous");
            if (msg.Mutations.HasFlag(PlantMutationFlags.CanScream))
                AppendMutation(mutList, "plant-analyzer-mut-screaming");
        }
        Mutations.Text = Loc.GetString("plant-analyzer-mutations", ("value", mutList.ToString()));

        var specList = msg.Speciation.Length == 0
            ? IndentedNewline + Loc.GetString("plant-analyzer-speciation-none")
            : string.Concat(msg.Speciation.Select(s => IndentedNewline + Loc.GetString(s)));
        Speciation.Text = Loc.GetString("plant-analyzer-speciation", ("value", specList));
    }

    private static void AppendMutation(StringBuilder sb, string key)
    {
        sb.Append(IndentedNewline);
        sb.Append(Loc.GetString(key));
    }

    private static string BuildList(string[] items)
    {
        if (items.Length == 0)
            return " " + Loc.GetString("plant-analyzer-none");
        var sb = new StringBuilder();
        foreach (var item in items)
        {
            sb.Append(IndentedNewline);
            sb.Append(item);
        }
        return sb.ToString();
    }
}
