using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client.Administration.UI.AdminObjectives.Components;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectivesTitle : Control
{
    public AdminObjectivesTitle()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMarkupPermissive(string text)
    {
        Text.SetMarkupPermissive($"[bold]{text}[/bold]");
    }
}

