using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client.Administration.UI.AdminObjectives.Components;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveGroup : Control
{
    public AdminObjectiveGroup(Model model) : this()
    {
        SetObjectives(model);
    }

    public AdminObjectiveGroup()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetObjectives(Model model)
    {
        Title.SetMarkupPermissive(model.Title);

        foreach (var objective in model.Objectives)
        {
            Objectives.AddChild(new AdminObjectiveItem(objective));
        }
    }

    public record Model(string Title, List<AdminObjectiveItem.Model> Objectives);
}

