using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Omu.Client.Administration.UI.AdminObjectives.Components;

[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveItem : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public AdminObjectiveItem(Model model) : this()
    {
        SetObjective(model);
    }

    public AdminObjectiveItem()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetObjective(Model model)
    {
        var sprite = _entityManager.System<SpriteSystem>();

        if (model.Icon is not null)
        {
            ObjectiveIcon.Texture = sprite.Frame0(model.Icon);
            ObjectiveSprite.Visible = false;
        }

        if (model.IconEntity is not null)
        {
            ObjectiveSprite.SetEntity(model.IconEntity.Value);
            ObjectiveIcon.Visible = false;
        }

        var title = model.Title;

        if (model.Progress.HasValue)
        {
            var percentColor = model.Progress == 0 ? Color.Red : model.Progress >= 1 ? Color.Green : Color.Yellow;

            title = $"{title} [color={percentColor.ToHex()}]{(int) (model.Progress * 100)}%[/color]";
        }

        ObjectiveName.SetMessage(FormattedMessage.FromMarkupPermissive(title));

        if (string.IsNullOrWhiteSpace(model.Description))
            ObjectiveDescription.Visible = false;
        else
            ObjectiveDescription.SetMessage(FormattedMessage.FromMarkupPermissive(model.Description));
    }

    public sealed class Model
    {
        public string Title { get; }
        public string? Description { get; }
        public SpriteSpecifier? Icon { get; }
        public NetEntity? IconEntity { get; }
        public float? Progress { get; }

        public Model(SpriteSpecifier icon, string title, string? description = null, float? progress = null)
        {
            Title = title;
            Description = description;
            Icon = icon;
            Progress = progress;
        }

        public Model(NetEntity icon, string title, string? description = null, float? progress = null)
        {
            Title = title;
            Description = description;
            IconEntity = icon;
            Progress = progress;
        }
    }
}
