- type: startingGear
  parent: ERTChaplainGearStarlightEVA
  id: ERTChaplainGearStarlight
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatFez
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterVestWebEliteCentcomm

- type: startingGear
  id: ERTChaplainGearStarlightEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Omu
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentCommNoThermal # Omu
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetCentCom
    belt: ChainsawSword
    neck: ClothingNeckStoleChaplain
    pocket2: WeaponPistolMk58 # Omu
  storage:
    back:
    - JugWater
    - JugWater
    - CosmicCenser
    - WeaponDisablerSMG
    - Handcuffs
    - Handcuffs
    - BibleNanoTrasen
    - BodyBagFolded
    - MagazinePistol # Omu
    - DeviceDesynchronizer
    - MedkitCombatFilled
