// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Omu.Revs;

// I HATE UI CODE I HATE UI CODE

[GenerateTypedNameReferences]
public sealed partial class RevObjectiveWindow : DefaultWindow
{

    public event Action<string>? OnObjectiveEntered;

    public RevObjectiveWindow()
    {
        RobustXamlLoader.Load(this);

        ObjectiveLineEdit.OnTextEntered += e => OnObjectiveEntered?.Invoke(e.Text);
    }


    public void SetCurrentObjective(string objective)
    {
        ObjectiveLineEdit.Text = objective;
    }

    //I'll keep marty's code, its probably gonna come in handy later
    public void SetUiText(string? titleBar, string? descriptorBar)
    {
        if (titleBar != null)
            Title = titleBar;

        if (descriptorBar != null)
            CurrentObjective.Text = descriptorBar;
    }
}
