// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control
    {
        // [Dependency] private readonly IConfigurationManager _config = default!;
        [Dependency] private readonly IClientConsoleHost _console = default!;

        public RoundTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            EndRoundButton.OnPressed += _ => _console.ExecuteCommand("endround");
            RestartRoundButton.OnPressed += _ => _console.ExecuteCommand("restartround");
            RestartRoundNowButton.OnPressed += _ => _console.ExecuteCommand("restartroundnow");
        }
    }
}
