- type: playTimeTracker
  id: JobCentCommIntern

- type: playTimeTracker
  id: JobCentCommDireggtor

- type: playTimeTracker
  id: JobTransitPrisoner

- type: playTimeTracker
  id: JobLogisticsAssistant

- type: playTimeTracker
  id: JobCourier

- type: playTimeTracker
  id: JobNanoTrasenSpectre

- type: playTimeTracker
  id: JobERTChaplainBlue

- type: playTimeTracker
  id: JobERTEngineerBlue

- type: playTimeTracker
  id: JobERTJanitorBlue

- type: playTimeTracker
  id: JobERTLeaderBlue

- type: playTimeTracker
  id: JobERTMedicalBlue

- type: playTimeTracker
  id: JobERTSecurityBlue

- type: playTimeTracker
  id: JobCustodii

- type: playTimeTracker
  id: JobSecuritySergeant

- type: playTimeTracker
  id: JobMedicalMedicus

- type: playTimeTracker
  id: JobEngineeringForeman

- type: playTimeTracker
  id: JobCargoBosun

- type: playTimeTracker
  id: JobScienceProfessor
