// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client._Omu.Preferences;
using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Omu.Lobby.Ui;

[GenerateTypedNameReferences]
public sealed partial class JobPriorityBoard : BoxContainer
{
    private const int ColumnBudget = 18;

    private static readonly JobPriority[] Priorities =
        [JobPriority.Never, JobPriority.Low, JobPriority.Medium, JobPriority.High];

    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IClientPreferencesManager _preferences = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly JobRequirementsManager _requirements = default!;

    private readonly Dictionary<JobPriority, PanelContainer> _columns = new();
    private readonly Dictionary<JobPriority, GridContainer> _grids = new();
    private CharacterQueueSystem? _characterQueue;
    private PlayerPreferences? _shownPreferences;
    private JobIcon? _dragged;
    private TextureRect? _ghost;

    public CheckBox DragToggle { get; } = new()
    {
        Text = Loc.GetString("job-priority-board-allow-dragging"),
        ToolTip = Loc.GetString("job-priority-board-allow-dragging-tooltip"),
    };

    public JobPriorityBoard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var priority in Priorities)
        {
            if (priority != JobPriority.Never)
            {
                AddChild(new PanelContainer
                {
                    MinSize = new Vector2(2, 0),
                    StyleClasses = { StyleClass.Highlight },
                });
            }

            var grid = new GridContainer
            {
                HorizontalAlignment = HAlignment.Center,
                MinSize = priority == JobPriority.High ? new Vector2(40, 40) : Vector2.Zero,
            };

            var priorityName = priority.ToString().ToLowerInvariant();
            var header = new Label
            {
                Text = Loc.GetString($"humanoid-profile-editor-job-priority-{priorityName}-button"),
                HorizontalAlignment = HAlignment.Center,
                StyleClasses = { StyleClass.LabelKeyText },
            };

            var column = new PanelContainer
            {
                Children =
                {
                    new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                        Margin = new Thickness(6, 2),
                        Children = { header, grid },
                    },
                },
            };

            _columns[priority] = column;
            _grids[priority] = grid;
            AddChild(column);
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _characterQueue = _entities.System<CharacterQueueSystem>();
        _characterQueue.Updated += Refresh;
        _requirements.Updated += Refresh;
        Refresh();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        if (_characterQueue is { } queue)
            queue.Updated -= Refresh;

        _characterQueue = null;
        _requirements.Updated -= Refresh;
        CancelDrag();
    }

    protected override void VisibilityChanged(bool newVisible)
    {
        base.VisibilityChanged(newVisible);

        if (!newVisible)
            CancelDrag();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!ReferenceEquals(_preferences.Preferences, _shownPreferences))
            Refresh();

        if (_ghost == null)
            return;

        var mouse = _ui.MousePositionScaled.Position;
        LayoutContainer.SetPosition(_ghost, mouse - _ghost.Size / 2);

        foreach (var column in _columns.Values)
        {
            if (column.GlobalRect.Contains(mouse))
                column.AddStyleClass(StyleClass.Highlight);
            else
                column.RemoveStyleClass(StyleClass.Highlight);
        }
    }

    private void Refresh()
    {
        if (_characterQueue is not { } queue)
            return;

        _shownPreferences = _preferences.Preferences;
        CancelDrag();

        foreach (var grid in _grids.Values)
        {
            grid.RemoveAllChildren();
        }

        var sprites = _entities.System<SpriteSystem>();
        foreach (var job in GetOrderedJobs())
        {
            if (!_requirements.IsAllowed(job, null, out _))
                continue;

            var priority = queue.State.JobPriorities.GetValueOrDefault(job.ID, JobPriority.Never);
            var texture = sprites.Frame0(_prototypes.Index(job.Icon).Icon);
            var chances = queue.GetJobChances(job);
            var tooltip = chances.Count == 0
                ? Loc.GetString("job-priority-board-no-character", ("job", job.LocalizedName))
                : string.Join("\n", chances
                    .Select(c => Loc.GetString("job-priority-board-chance",
                        ("name", c.Character.Name),
                        ("percent", (int) MathF.Round(c.Chance * 100))))
                    .Prepend(job.LocalizedName));

            _grids[priority].AddChild(new JobIcon(this, job, priority, texture, tooltip));
        }

        BalanceColumns();
    }

    private void BalanceColumns()
    {
        var rows = 1;
        while (_grids.Values.Sum(grid => ColumnsFor(grid, rows)) > ColumnBudget)
        {
            rows++;
        }

        foreach (var grid in _grids.Values)
        {
            grid.Columns = Math.Max(1, ColumnsFor(grid, rows));
        }
    }

    private static int ColumnsFor(GridContainer grid, int rows)
    {
        return (grid.ChildCount + rows - 1) / rows;
    }

    private List<JobPrototype> GetOrderedJobs()
    {
        var departments = _prototypes.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .ToList();
        departments.Sort(DepartmentUIComparer.Instance);

        var jobs = new List<JobPrototype>();
        foreach (var department in departments)
        {
            var departmentJobs = department.Roles
                .Select(role => _prototypes.Index(role))
                .Where(job => job.SetPreference && !jobs.Contains(job))
                .ToList();

            departmentJobs.Sort(JobUIComparer.Instance);
            jobs.AddRange(departmentJobs);
        }

        return jobs;
    }

    private void BeginDrag(JobIcon icon)
    {
        if (!DragToggle.Pressed)
            return;

        CancelDrag();
        _dragged = icon;
        _ghost = new TextureRect
        {
            Texture = icon.Texture,
            TextureScale = icon.TextureScale,
            MouseFilter = MouseFilterMode.Ignore,
        };

        _ui.PopupRoot.AddChild(_ghost);
    }

    private void EndDrag()
    {
        if (_dragged is not { } icon)
            return;

        var mouse = _ui.MousePositionScaled.Position;
        CancelDrag();

        foreach (var (priority, column) in _columns)
        {
            if (priority != icon.Priority && column.GlobalRect.Contains(mouse))
                _characterQueue?.SetJobPriority(icon.Job.ID, priority);
        }
    }

    private void CancelDrag()
    {
        _dragged = null;
        _ghost?.Orphan();
        _ghost = null;

        foreach (var column in _columns.Values)
        {
            column.RemoveStyleClass(StyleClass.Highlight);
        }
    }

    private sealed class JobIcon : TextureRect
    {
        private readonly JobPriorityBoard _board;

        public readonly JobPrototype Job;
        public readonly JobPriority Priority;

        public JobIcon(JobPriorityBoard board, JobPrototype job, JobPriority priority, Texture texture, string tooltip)
        {
            _board = board;
            Job = job;
            Priority = priority;
            Texture = texture;
            TextureScale = new Vector2(priority == JobPriority.High ? 5 : 2.5f);
            HorizontalAlignment = HAlignment.Center;
            VerticalAlignment = VAlignment.Center;
            MouseFilter = MouseFilterMode.Stop;
            ToolTip = tooltip;
        }

        protected override void KeyBindDown(GUIBoundKeyEventArgs args)
        {
            base.KeyBindDown(args);

            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _board.BeginDrag(this);
            args.Handle();
        }

        protected override void KeyBindUp(GUIBoundKeyEventArgs args)
        {
            base.KeyBindUp(args);

            if (args.Function == EngineKeyFunctions.UIClick)
                _board.EndDrag();
        }
    }
}
